import React, { Component} from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

import Logo from "../images/Logo.png"
import close_Icon from "../images/close-Icon.png"
import white_logo from "../images/white-logo.png"
import Group_7 from "../images/Group-7.png"
import quote from "../images/quote.png"
import drbrownstein from "../images/drbrownstein.png"
import unvi from "../images/unvi.png"
import step1 from "../images/step1.png"
import appstore_bt from "../images/appstore-bt.png"
import playstore_bt from "../images/playstore-bt.png"
import step2 from "../images/step2.png"
import step3 from "../images/step3.png"
import step4 from "../images/step4.png"
import step5 from "../images/step5.png"
import step6 from "../images/step6.png"
import step7 from "../images/step7.png"
import step8 from "../images/step8.png"
import bene_1 from "../images/bene1.png"
import benefits from "../images/benefits2.png"
import bene_03 from "../images/bene03.png"
import Image_2 from "../images/Image_2.png"
import appstore from "../images/appstore.png"
import googleplay from "../images/googleplay.png"
import test_kit from "../images/test-kit.png"
import how_anti from "../images/how-anti.jpg"
import anti_ from "../images/anti_1.png"
import igm from "../images/igm.png"
import igg from "../images/igg.png"
import result_igm from "../images/result-igm.png"
import result_both from "../images/result-both.png"
import result_igg from "../images/result-igg.png"
import result_neg from "../images/result-neg.png"
import invalid from "../images/invalid.png"
import data_priv from "../images/data-priv.png"
import cards from "../images/2cards.png"
import _Ryan_Dranginis from "../images/4-Ryan-Dranginis.jpg"
import _Jesus_Gonzalez from "../images/3-Jesus-Gonzalez.jpg"
import _Matt_McCord from "../images/2-Matt-McCord.jpg"
import _Jon_Carder from "../images/1_Jon-Carder.jpg"
import _Blake_Jendrusch from "../images/43-Blake-Jendrusch.jpg"
import _Jeremy_Schumann from "../images/42-Jeremy-Schumann.jpeg"
import _Jordan_Ames from "../images/41-Jordan-Ames.jpg"
import _Ghaleb_Hamdan from "../images/39-Ghaleb-Hamdan.jpg"
import _Eric_Ostrowski from "../images/38-Eric-Ostrowski.jpg"
import _Anand_Bhatt from "../images/36-Anand-Bhatt.jpg"
import _Pete_Janda from "../images/35-Pete-Janda.jpg"
import _Adam_Eidelson from "../images/34-Adam-Eidelson.jpg"
import _Jonathan_Balleras from "../images/33-Jonathan-Balleras.jpg"
import _Eric_Weiss from "../images/32-Eric-Weiss.jpg"
import _Mark_Tholking from "../images/31-Mark-Tholking.jpg"
import _Ryan_Wojciechowski from "../images/30-Ryan-Wojciechowski.jpg"
import _Kevin_Martignetti from "../images/29-Kevin-Martignetti.jpg"
import _Peter_Haist from "../images/28-Peter-Haist.jpg"
import _Andrea_Giralt from "../images/27-Andrea-Giralt.jpg"
import _Paul_Williams from "../images/26-Paul-Williams.jpg"
import _Meredith from "../images/25-Meredith.jpg"
import _Dr_Lane from "../images/24-Dr.-Lane.jpg"
import _Dr_Sam_Niedbala from "../images/23-Dr.-Sam-Niedbala.jpg"
import _mona_update from "../images/22-mona-update.png"
import _Dr_Sameer_Berry from "../images/21-Dr.-Sameer-Berry.jpg"
import _mike from "../images/20-mike.png"
import _larson from "../images/19-larson.png"
import _paula from "../images/18-paula.png"
import _Dr_Robert_Buechel from "../images/17-Dr.-Robert-Buechel.jpg"
import _James_Bausano from "../images/16-James-Bausano.jpg"
import _John_Norris from "../images/15-John-Norris.jpg"
import _Trish_Pavlecich from "../images/14-Trish-Pavlecich.jpg"
import _Lee_O_Donovan from "../images/13-Lee-O_Donovan.jpg"
import _Kristen_Hlozek from "../images/12-Kristen-Hlozek.jpg"
import _Matty_Vee from "../images/11-Matty-Vee.jpg"
import _Dan_Riley from "../images/10-Dan-Riley.jpg"
import _Bucky_Markus from "../images/9-Bucky-Markus.jpg"
import _Andrew_Beinbrink from "../images/8-Andrew-Beinbrink.jpg"
import _Christian_Chasmer from "../images/7-Christian-Chasmer.jpg"
import _Kyle_Brown from "../images/6-Kyle-Brown.jpg"
import _Doug_Lorenzen from "../images/5-Doug-Lorenzen.jpg"
import prev from "../images/prev.png"
import next from "../images/next.png"
import Icon from "../images/Icon.png"
import Icon_checkbox from "../images/Icon-checkbox.png"
import fb from "../images/fb.png"
import tw from "../images/tw.png"
import li from "../images/li.png"
import em from "../images/em.png"
import expand from "../images/expand.png"
import close from "../images/close.png"

class coronaPage extends Component {
	render() {
	return (
	<Layout>
    <SEO title="page 2" />
<span>test</span>
  </Layout>
	)
	}
}

export default coronaPage